name: Deploy to EKS

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

steps:
- name: Checkout
uses: actions/checkout@v4

- name: Configure AWS
uses: aws-actions/configure-aws-credentials@v4
with:
aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
aws-region: ap-south-1

- name: Configure kubectl
run: |
aws eks update-kubeconfig --region ap-south-1 --name week4-cluster

- name: Deploy
run: |
kubectl apply -f deployment.yaml
kubectl apply -f service.yaml
